/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/

import Strata.MetaVerifier

open Strata

/-
Regression test for issue #1142:
Datatype tester/selector incorrectly resolved as a free variable when the
referenced datatype is declared first among 4+ datatypes.

Root cause: `initFVarIsOp` counted one entry per *command* (one `false` per
`datatype` command), but the `GlobalContext` adds many entries per datatype —
the type itself plus all constructors, testers, and selectors generated by
templates. When the referenced datatype was first, its tester/selector
`fvar` indices fell inside the misaligned `fvarIsOp` array and got `false`
(type) instead of `true` (op). The fix: remove `fvarIsOp` and always derive
op-vs-type from `GlobalContext.vars[i]`, which is correct for all symbols.
-/

-- Failing case from the bug report: `color` is declared first among 4
-- datatypes; `get_val` references `color..iscolor_Red` and `color..color_Red_0`.
private def datatypeTesterFirstSeed : Strata.Program :=
#strata
program Boole;

datatype color {
  color_Red(color_Red_0 : int),
  color_Blue(color_Blue_0 : int)
};
datatype tag1 {
  tag1_only()
};
datatype tag2 {
  tag2_only()
};
datatype tag3 {
  tag3_only()
};
function get_val (c : color) : int {
  if color..iscolor_Red(c) then color..color_Red_0(c) else color..color_Blue_0(c)
}
#end

/-- info:
Obligation: get_val_body_calls_color..color_Red_0_0
Property: assert
Result: ✅ pass

Obligation: get_val_body_calls_color..color_Blue_0_1
Property: assert
Result: ✅ pass-/
#guard_msgs in
#eval Strata.Boole.verify "cvc5" datatypeTesterFirstSeed (options := .quiet)

example : Strata.smtVCsCorrect datatypeTesterFirstSeed := by
  gen_smt_vcs
  all_goals (try grind)
